---
## This playbook deploys the whole application stack in this site.

# Apply common configuration to all hosts
- hosts: all
  remote_user: opc
  sudo: True
  roles:
  - common

# Configure and deploy database servers.
- hosts: dbservers
  remote_user: opc
  sudo: True
  roles:
  - db

# Configure and deploy the web servers. Note that we include two roles here,
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- hosts: webservers1
  remote_user: opc
  sudo: True
  roles:
  - base-apache
  - web01

- hosts: webservers2
  remote_user: opc
  sudo: True
  roles:
  - base-apache
  - web02


# Configure and deploy the load balancer(s).
- hosts: lbservers
  remote_user: opc
  sudo: True
  roles:
  - haproxy
